services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=repetiteur
    # uncomment for debugging
    # command: ["postgres", "-c", "log_statement=all"]
    ports:
      # Expose the database on the host machine on port 5432
      # for dev puposes only
      - "5432:5432"
    volumes:
      # use a named volume to persist the database data
      - repetiteur-db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  repetiteur:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/repetiteur
      - |
        ROCKET_DATABASES={
          postgres={url=postgres://postgres:postgres@postgres/repetiteur},
          redis={url=redis://redis:6379}
        }
    ports:
      - 8000:8000
    volumes:
      - ./:/app/

volumes:
  repetiteur-db-data:
