DROP TABLE UserPreferences;
DROP TABLE LessonHistory;
DROP TABLE QuestionHistory;
DROP TABLE CourseUsers;
DROP TABLE Questions;
DROP TABLE Lessons;
DROP TABLE Courses;
DROP TABLE Users;
DROP TABLE Roles;
